ministryofjustice/create-and-vary-a-licence

- .circleci/config.yml
Updates orb version 3.6 -> 3.8
> Update to circle orb to 3.8 to get around Veracode scanning issue.

- server/services/communityService.ts
Small, speculative change to test whether the username is important when connecting to the community api.
I suspect that where we supplied a username it will try to validate it as a Delius user, and fail.
> CVL-28: Community API remove non-Delius username from client token.

- helm_deploy/values-dev.yaml
The Gotenberg container is referenced by its service name within the cluster, so its URL from within the create-and-vary-a-licence service should have been `http://create-and-vary-a-licence-gotenberg:3000` - now corrected.
> CVL-12: Use correct reference to gotenberg service

- helm_deploy/values-dev.yaml
After some head-scratching and thinking - I think each service should reference each other using the service name on the default port 80 for converting HTML to PDF, and for the links within the HTML to reference assets like CSS.
> CVL-12: use service name on port 80 in both directions

- .circleci/config.yml
- package-lock.json
- package.json
In this PR
* Use farsight-alerts in place of farsight-devs for alerts (public channel)
* Update sass version
* Update govuk-frontend version - fails the check_outdated circle job overnight
> CVSL-96: Updated alert channel to public channel and updated dependencies

- helm_deploy/values-dev.yaml
- integration_tests/integration/createLicence.spec.js
- integration_tests/mockApis/licence.js
- integration_tests/pages/confirmation.js
- integration_tests/pages/page.js
- integration_tests/plugins/index.js
- server/config.ts
- server/routes/creatingLicences/handlers/confirmation.test.ts
- server/routes/creatingLicences/handlers/confirmation.ts
- server/utils/nunjucksSetup.ts
- server/views/layout.njk
- server/views/pages/create/confirmation.njk
- server/views/pages/create/confirmation.test.ts
This PR:
* Adds the `fetchLicenceMiddleware` to the confirmation page and shows licence details.
* Adds configurable links for the phase banner and exit survey - by environment (in nunjucksSetup module - app.locals)
* Adds a `Return to home` button
* Template tests using cheerio to check content
* Puts some scaffolding in place for integration tests - licenceApi, getLicence stub, confirmation page definition (not used yet)
> CVSL-116: Confirmation page

- feature.env
- integration_tests/integration/createLicence.spec.ts
- integration_tests/mockApis/community.ts
- integration_tests/plugins/index.ts
- server/data/communityApiClient.test.ts
- server/data/probationSearchApiClient.test.ts
- server/routes/creatingLicences/handlers/caseload.test.ts
- server/routes/creatingLicences/handlers/caseload.ts
- server/routes/creatingLicences/index.ts
- server/routes/spikes/handlers/spikes.ts
- server/services/communityService.ts
* Added wiremock for community api
*  Query delius for a staff member's caseload to populate the caseload list. 
_**From now on, we need to log in a user in Auth, who also is a user in DELIUS, who also has a caseload, otherwise, the caseload screen will just have 1 stubbed case**_
> CVSL-131: Pull staff caseload from Delius

- integration_tests/integration/createLicence.spec.ts
- integration_tests/mockApis/licence.ts
- integration_tests/pages/additionalConditionsQuestion.ts
- integration_tests/pages/bespokeConditions.ts
- integration_tests/pages/bespokeConditionsQuestion.ts
- integration_tests/plugins/index.ts
- server/@types/licenceApiImport/index.d.ts
- server/data/licenceApiClient.test.ts
- server/data/licenceApiClient.ts
- server/data/licenceApiClientTypes.ts
- server/routes/creatingLicences/handlers/bespokeConditions.test.ts
- server/routes/creatingLicences/handlers/bespokeConditions.ts
- server/routes/creatingLicences/index.ts
- server/routes/creatingLicences/types/bespokeConditions.ts
- server/routes/creatingLicences/types/yesOrNo.ts
- server/services/licenceService.ts
- server/views/pages/create/bespokeConditions.njk
- server/views/pages/create/bespokeConditionsQuestion.njk
Includes:
* Prepopulating multiple bespoke conditions where they exist for a licence
* Storing bespoke conditions into the DB via the API
* Using the `fetchLicence` middleware for this route
* Allowing the addition of one or more bespoke conditions
* Filtering any blank / empty conditions
* Unit tests
* Integration test - incorporate into the main flow for creating a licence
> CVSL-111:  Add / update for multiple bespoke conditions

- helm_deploy/create-and-vary-a-licence/Chart.yaml
- helm_deploy/create-and-vary-a-licence/values.yaml
- helm_deploy/values-dev.yaml
Part of a fiendish plan to avoid the data mismatch between Delius and Nomis.
This deploys a service in a container in the namespace which pretends to be the Community API for /staff and /managedOffenders, and returns a list of people who are known in Nomis via the prisoner offender search API. 
We know the Community API works well, but we cant setup the appropriate data there without breaking the Delius TEST environment for the Delius work, so this is the next best thing.
> CVSL-98: Deployment of a container to stub the Community API caseload.

- integration_tests/integration/createLicence.spec.ts
- integration_tests/mockApis/licence.ts
- integration_tests/pages/additionalConditionInput.ts
- server/config/conditions.ts
- server/routes/creatingLicences/types/additionalConditionInputs/curfewTerms.ts
- server/routes/creatingLicences/types/time.ts
- server/services/licenceService.ts
- server/utils/nunjucksSetup.ts
- server/validators/decorators.ts
- server/validators/isSimpleTimeAfter.test.ts
- server/validators/isSimpleTimeAfter.ts
- server/views/formBuilder.njk
- server/views/formBuilder.test.ts
- server/views/pages/create/additionalConditionInput.njk
- server/views/partials/datePicker.njk
- server/views/partials/timePicker.njk
- server/views/partials/timePicker.test.ts
- Added conditional reveal inputs nested beneath radio buttons
- Recursive formBuilder nunjucks macro which passes in the conditional reveal inputs
- Added a field decorator for validating that a time entered is after another time entered
- Conditional reveal field inputs have their parent's value stored in DB and displayed on the check your answers page, as below. Cannot easily overwrite the value of the radio button with the value of the conditional reveal because then it's hard to reconstruct the form when arriving from the change links.
> CVSL-184: Added conditional radio button

- server/data/prisonApiClient.test.ts
- server/services/prisonerService.ts
When no offender image exists, this sends the placeholder image instead.
> CVSL-209 missing image placeholder in licence documents

- server/@types/licenceApiImport/index.d.ts
- server/config/conditions.ts
- server/data/licenceApiClient.test.ts
- server/routes/approvingLicences/handlers/approvalView.test.ts
- server/routes/approvingLicences/handlers/approvalView.ts
- server/services/licenceService.ts
- server/views/pages/licence/AP.njk
- server/views/pages/licence/AP_PSS.njk
- server/views/pages/licence/PSS.njk
* Use stored approver's name in signatures
* Supply approvers full name in status change for approval.
* Add missing .tpl templates for newly entered conditions.
> CVSL-206 - use the approvers full name in signatures

- integration_tests/integration/approveLicence.spec.ts
- integration_tests/integration/rejectLicence.spec.ts
- integration_tests/integration/viewAndPrintLicence.spec.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/licence.ts
- integration_tests/pages/index.ts
- integration_tests/pages/printLicenceHtmlPage.ts
- integration_tests/pages/viewALicence.ts
- integration_tests/pages/viewCases.ts
- integration_tests/plugins/index.ts
This PR:
* Creates page objects for view cases, view licence and HTML printed licence
* Implements a click-through journey to view and print a licence
* Verifies accessibility of pages
* Verifies that the printed licence contains key structure and data items.
* It overrides the PDF print link with the HTML version (same stylesheet, structure and content, just easier to verify :-) )
> CVSL-208: Integration test for view and print licence journey.

- docker-compose.yml
- server/config/conditions.ts
- server/routes/creatingLicences/types/additionalConditionInputs/noContactWithVictim.ts
- server/routes/creatingLicences/types/additionalConditionInputs/unsupervisedContact.ts
- server/routes/creatingLicences/types/address.ts
- server/routes/creatingLicences/types/time.ts
- server/services/licenceService.ts
- Removed "Add another" options from social services department as agreed
- Do not persist empty date/time/address in the case that they are optional fields
- Configured `docker-compose.yml` to run `create-and-vary-a-licence-api` as a container locally for convenience & local dev (still uses auth in dev)
> CVSL-220: Remove "Add another" from social services department fields in additional conditions

- helm_deploy/create-and-vary-a-licence/values.yaml
- server/config.ts
- server/middleware/setUpWebSecurity.ts
- server/utils/nunjucksSetup.ts
- server/views/layout.njk
* Also added TAG_MANAGER_CONTAINER_ID into dev K8s secrets.
* Setup two GA properties (CVL-prod, CVL-non-prod)
* Setup two GTM containers (CVL-dev, CVL-preprod)
* Setup two data streams in GA to send GA4 analytics to GA non-prod property.
* Only one way to see if all this works..
> CVSL-27: Add google tag manager id to the service

- assets/js/govukFrontendInit.js
- server/routes/creatingLicences/types/additionalConditionInputs/drugTestLocation.ts
- server/routes/creatingLicences/types/additionalConditionInputs/namedIndividuals.ts
- server/routes/creatingLicences/types/additionalConditionInputs/namedOrganisation.ts
- server/routes/creatingLicences/types/additionalConditionInputs/noContactWithVictim.ts
- server/routes/creatingLicences/types/additionalConditionInputs/specifiedItem.ts
- server/validators/decorators.ts
- server/validators/hasAtLeastOne.test.ts
- server/validators/hasAtLeastOne.ts
- Add another validation had been accepting `[""]` as a valid input
- New decorator filters out empty values before checking that the array is empty
- Also clicking the back link from a page with a validation error will direct to the page before, wheras it had been directing to the same page with the error message cleared
> CVSL-234: Fix add another validation + back link from error

- integration_tests/integration/createLicence.spec.ts
- integration_tests/mockApis/licence.ts
- integration_tests/pages/approvalView.ts
- integration_tests/pages/viewALicence.ts
- server/config/conditions.ts
- server/routes/approvingLicences/handlers/approvalView.test.ts
- server/routes/approvingLicences/handlers/approvalView.ts
- server/routes/creatingLicences/handlers/additionalLicenceConditions.ts
- server/routes/creatingLicences/handlers/additionalLicenceConditionsQuestion.ts
- server/routes/creatingLicences/handlers/checkAnswers.test.ts
- server/routes/creatingLicences/handlers/checkAnswers.ts
- server/routes/viewingLicences/handlers/viewLicence.test.ts
- server/routes/viewingLicences/handlers/viewLicence.ts
- server/services/licenceService.ts
- server/utils/conditionsProviderExpand.test.ts
- server/views/pages/approve/view.njk
- server/views/pages/create/checkAnswers.njk
- server/views/pages/create/checkAnswers.test.ts
- server/views/pages/view/view.njk
- server/views/pages/view/view.test.ts
- server/views/partials/additionalLicenceConditionsSummary.njk
- server/views/partials/additionalPssConditionsSummary.njk
- server/views/partials/bespokeConditionsSummary.njk
- server/views/partials/inductionMeetingDetailsSummary.njk
* Lots of content changes (titles, condition counters, change links and wording).
* Expanded condition text with in-line values shown on all summary screens.
* Removed rejection link (hidden) - but integration test forces its use.
* Updated unit and integration tests for all content changes.
* Use of short-names for some categories on summary pages (replaces full category, if present, and written to DB via API)
* Adds missing probation regions, and appends `..Probation Region`" to all e.g. `London Probation Region` - so condition sentences don't need to be changed.
* Simplified tests by defining and re-using a single licence object (using spread syntax to change type/status).
> CVSL-218 Check your answers, view, print and approve a licence.

- server/utils/urlAccessByStatus.test.ts
- server/utils/urlAccessByStatus.ts
RegExp not quite right. Now fixed & test to confirm.
> CVSL-279: Fixed allowed URLs (again) - missing asterisk to match with multiple digits, not one.

- server/utils/urlAccessByStatus.test.ts
- server/utils/urlAccessByStatus.ts
Approval flow sets the status to APPROVED and then shows the confirmation - needed confirmation URL in allow list for APPROVED.
Approval flow sets the status to REJECTED and then shows a rejected confirmation - needed confirmation URL in allow list for REJECTED.
> CVSL-281: Fixed missing URLs in allowed list.

- server/data/hmppsRestClient.test.ts
- server/data/hmppsRestClient.ts
- server/middleware/fetchLicenceMiddleware.test.ts
- server/middleware/fetchLicenceMiddleware.ts
* Used Promise-then-catch notation in http client
* Wrapped `fetchLicenceMiddleware` in try-catch to handle rejected promise as is done in `populateCurrentUser` middleware
* Added test coverage for the STREAM util in httpClient
> CVSL-273: Handle rejected promise in fetch licence middleware

- package-lock.json
- package.json
- server/views/pages/create/checkAnswers.test.ts
A further ticket has been created to check through the govuk-frontend release notes which may need some small changes in our code, but for now the journeys look good and tests are passing.
> CVSL-287: Update dependencies to fix overnight scans. 

- Dockerfile
This is to fix the failing deployment, which complains it cannot create the /app/uploads directory.
> CVSL-304: Create temp upload directory and set permissions during image build

- assets/js/govukFrontendInit.js
- assets/sass/application-ie8.sass
- assets/sass/components/_link-button.scss
- server/views/layout.njk
Three things here:
* Set the focus property on the link button (names on case list view)
* Updated the SCCS modules included in the IE version of application.css - missing modules.
* Experimental - add an empty main div with a tabindex -1 - attempt to get IE11 to tab into the content for keyboard-only navigation.
> CVSL-285: Link button focus. IE SCSS updates.

- .circleci/config.yml
- integration_tests/integration/eventHandlers.spec.ts
- integration_tests/mockApis/auth.ts
- integration_tests/mockApis/licence.ts
- integration_tests/plugins/index.ts
- integration_tests/support/events.ts
- integration_tests/wiremock.ts
- server/config.ts
- server/listeners/eventHandlers/domainEvents/index.ts
- Created custom CircleCi executor including localstack (pathfinder and manage intelligence have done this, should add it to the orb for future and other projects?)
- Created queues in localstack for integration test
- Added new integration test helper to push events onto the stack
- Added new helper to check wiremock `count` endpoint to assert the correct endpoint is called after consuming an event
- Handled rejected promise from the event handler
> CVSL-317: Add integration tests for AWS event consumer

- .circleci/config.yml
- Pathfinder uses the `hmpps/wait_till_ready` command, but this will wait for ports to start accepting requests. This is not necessarily the same time that localstack is ready to start creating resources.
- Manage intelligence project simply waits 10 seconds.
- If this still experiences problems, we can do a more sophisticated check by logging out the localstack logs and grepping for "READY"
> Wait for 10 seconds for localstack to be ready before creating resources

- integration_tests/mockApis/community.ts
- server/@types/communityApiImport/index.d.ts
- server/@types/communityClientTypes.ts
- server/@types/managedCase.ts
- server/data/communityApiClient.test.ts
- server/data/communityApiClient.ts
- server/routes/creatingLicences/handlers/caseload.test.ts
- server/routes/creatingLicences/handlers/caseload.ts
- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
- server/services/communityService.test.ts
- server/services/communityService.ts
- server/views/pages/create/caseload.njk
- Refactored `caseloadService` to reuse the caseload filtering rules
- Cacheing can be introduced later if we feel we need it
- Increased test coverage of `caseloadService`
- Added new tab to caseload page
- Integrated with new `teams/managedCases` endpoint
- Removed the `currentOm` filter and replaced with the `?current=true` query parameter
> CVSL-308: Team caseload view

- package-lock.json
- package.json
`npm run security_audit`  - reported 2 issues
`npm audit fix` - updated Mocha and audit reporting clear.
Tests all passing.
> CVSL-345: Update dependencies to fix vulnerabilities x 2 in Mocha.

- assets/sass/application-ie8.sass
- assets/sass/application.sass
- assets/sass/components/_summary-card.scss
- server/@types/licenceApiClientTypes.ts
- server/enumeration/conditionType.ts
- server/routes/approvingVariations/handlers/varyRefer.test.ts
- server/routes/approvingVariations/handlers/varyRefer.ts
- server/routes/varyingLicences/handlers/reasonForVariation.test.ts
- server/routes/varyingLicences/handlers/reasonForVariation.ts
- server/routes/varyingLicences/handlers/variationSummary.test.ts
- server/routes/varyingLicences/handlers/variationSummary.ts
- server/services/licenceService.test.ts
- server/services/licenceService.ts
- server/utils/licenceComparator.test.ts
- server/utils/licenceComparator.ts
- server/views/customComponents/summaryCard/macro.njk
- server/views/customComponents/summaryCard/template.njk
- server/views/pages/vary-approve/request-changes.njk
- server/views/pages/vary/reasonForVariation.njk
- server/views/pages/vary/variationSummary.njk
- server/views/partials/variationDetails.njk
- server/views/partials/variedConditions.njk
- Implemented the following algorithm to compare two lists
- Added a custom CSS component, which would ideally be added to the MoJ design library. 
```
sort left-list and right-list
adds = {}
deletes = {}
get first right-item from right-list
get first left-item from left-list
while (either list has items)
if left-item < right-item or right-list is empty
add left-item to deletes
get new left-item from left-list
else if left-item > right-item or left-list is empty
add right-item to adds
get new right-item from right-list
else
get new right-item from right-list
get new left-item from left-list
```
> CVSL-417: Varied conditions comparison

- helm_deploy/values-prod.yaml
- server/config.ts
Switches on RESTRICT_ROLLOUT env variable in production.
Configures the set of prisons and probation areas which are allowed to access.
> CVSL-433: Restrict access to Wales probation area and prisons in production

- .circleci/config.yml
- docker-compose-dev.yml
- docker-compose-test.yml
- docker-compose.yml
- helm_deploy/create-and-vary-a-licence/values.yaml
- integration_tests/support/events.ts
- localstack/01-setup-queues.sh
- server/config.ts
- server/data/gotenbergApiClient.test.ts
- server/data/gotenbergClient.ts
- Apple have stopped manufacturing Macbooks with intel x86_64 chips
- New Macbooks have ARM architecture with the new M1 chip
- Some of the docker containers we use locally have not been packaged for ARM architecture, which means that running them locally either fails or is very slow, as the x86_64 architecture needs to be emulated
- Newer versions of these docker images do support ARM, so upgrading to those new versions solves this issue
> CVSL-441: Upgrade docker containers for ARM support

- package-lock.json
- package.json
Update typescript 4.6.2 -> 4.6.3 to resolve `check_outdated` error overnight.
> CVSL-473: Updating typescript to latest version

- integration_tests/integration/eventHandlers.spec.ts
- integration_tests/mockApis/community.ts
- integration_tests/mockApis/probationSearch.ts
- localstack/01-setup-queues.sh
- server/config.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.test.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.ts
- server/services/licenceService.test.ts
- server/services/licenceService.ts
- Identify the COM based on a cross-reference from probation-offender-search, rather than trusting the isResponsibleOfficer flag from community API
> CVSL-498: Fix POM being incorrectly identified as the COM

- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
* Removes the 18th April CRD cut-off from the case lists - we already have cases before this e.g. a release planned on 14th.
* No longer filters out empty/missing `conditionalReleaseDate` - it now allows for the `conditionalReleaseDate` or `releaseDate` or `confirmedReleaseDate` to be present - we've seen cases which should appear being filtered for this.
* Recalls unaffected by this change - there is a rule commented that we may decide to put in later.
* Tests updated - including vary caseloads with ACTIVE IN status altered to INACTIVE OUT - and still passing.
> CVSL-500 filter rule changes

- server/middleware/setUpStaticResources.ts
Gotenberg automatically searches for a favicon at `/favicon.ico`
> CVSL-505: Fix 404 throwing for favicon during PDF render

- integration_tests/integration/eventHandlers.spec.ts
- integration_tests/mockApis/community.ts
- integration_tests/plugins/index.ts
- integration_tests/wiremock.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.test.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.ts
- Tested using delius wiremock
- Also simplified the endpoint verification task during integration tests by reusing the `success` logic in one place
> CVSL-485: Assign the COM role on offender allocation

- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
* Remove the use of `releaseDate` as a driver for showing cases - this could bring in other types of licence (DTOs)
* Rely on `conditionalReleaseDate` or `confirmedReleaseDate` only
* Show recalls on case lists but make them unclickable - cannot create a licence - out of scope.
* Show BOTUS (breach of top-up supervision orders) cases on case lists but make them unclickable - cannot create a licence.
* Case list tests to confirm the above.
> CVSL-500: Caseload rules 

- integration_tests/integration/eventHandlers.spec.ts
- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.test.ts
- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.ts
This is part 1 of a 2-port change. Part 2 is in the API coming soon.
This change avoids updating the licence status whenever we get a dates-changed event.
It will be replaced by a notification to the COM (via the API) if any of the date changes are `material` to the licence.
This avoids the situation where licences are changed from APPROVED to IN_PROGRESS just prior to release, as it looks like the OMU staff update the release date near, or on, the day of release.
> CVSL-531: Avoid updating licence status for dates-changed events

- docker-compose-dev.yml
Add the postgresql container to docker-compose-dev.yaml - so will run this and other required containers when using DEV for auth, prison, community APIs etc.
> refs CVSL-540

- package-lock.json
- package.json
4.6.3 -> 4.6.4 to prevent overnight check_outdated job from failing build.
> CVSL-550: Updating typescript to latest (overnight job fail)

- server/services/licenceService.test.ts
- server/services/licenceService.ts
This bug affects audit events raised by the UI service only.
The moment time parsing was incorrectly using the 12-hour clock form `hh:mm:ss`.
It should (and now does) use the 24-hour clock format `HH:mm:ss` + tests updated.
> CVSL-545: Correct the audit event time format when raised from the UI service.

- server/routes/varyingLicences/handlers/timeline.test.ts
- server/routes/varyingLicences/handlers/timeline.ts
This moves the trigger to set the varied licence to the same point at which the variation is set to ACTIVE.
It was formerly doing this when the variation was APPROVED.
> CVSL-556: Set the varied licence to INACTIVE when the variation is activated.

- server/routes/creatingLicences/handlers/confirmCreate.test.ts
- server/routes/creatingLicences/handlers/confirmCreate.ts
- When confirmedReleaseDate was null, the original code was setting actualReleaseDate == todays date
> CVSL-243: Fix actualReleaseDate field when confirmedReleaseDate is null on the confirmCreatePage

- package-lock.json
- package.json
Failing overnight job `check-outdated` on govuk-frontend.
The new version release notes contain mostly fixes, and the one or two changes appear not to affect the service.
> CVSL-574: Updated govuk-frontend to 4.1.0 (fixes)

- server/routes/support/handlers/offenderDetail.test.ts
- server/routes/support/handlers/offenderDetail.ts
- server/services/caseloadService.test.ts
Ensure dates are present on the offender support page. Show "Not found" if date is not present.
> Ensure dates are present on the offender support page.

- server/views/pages/vary/confirmation.njk
Now refers to an email.
No change to logic
> CVSL-582 vary confirmation page text change

- server/views/pages/vary-approve/view.njk
- server/views/partials/variationDetails.njk
ACs:
Make date format 16 May 2022 (removing th / nd) 
Change grey secondary button to "Reject or request amendments"
> CVSL-582 date format and button text changed

- server/routes/creatingLicences/types/reasonForReferral.ts
- server/views/pages/vary-approve/request-changes.njk
ACs
Change H1 to Add reasons for declining the licence variation request 
Change accordion text to "View licence variation details" 
Change green button text to Continue 
Change error summary text to
There is a problem
You must add a reason for wanting to decline the variation request 
Change inline error message text
You must add a reason for wanting to decline the variation request
> CVSL-582 text changes for Add reasons page

- server/views/pages/vary-approve/approved.njk
- server/views/pages/vary-approve/variation-referred.njk
The changes were previously applied to wrong page (variation-referred.njk). 
Changes reversed and applied to correct page (approved.njk)
ACs
Change banner to Licence variation for [first name last name] approved
Change text under What happens next to:
The variation for [first name last name] has been approved with your digital signature.
We have sent an email notification to the probation practitioner.
They will be able to print and issue the licence.
Change green button text to "Return to case list" 
Vary approved page:
> CVSl 582 PDU head approval correction

- server/views/pages/vary-approve/variation-referred.njk
following decline of variation by PDU head
AC's:
Change banner to Licence variation for [first name last name] declined 
Change text under What happens next to
The variation for [first name last name] has been declined.
We have sent an email to the probation practitioner to notify them. 
They can amend and resend the variation or discard it.
Change green button text to "Return to case list" 
view:
> CVSL-582 text changes to confirmation page 

- server/views/pages/vary-approve/approved.njk
- server/views/pages/vary-approve/request-changes.njk
- server/views/pages/vary-approve/variation-referred.njk
PDU head approval journey
**refer**
Change H1 to Add reasons for declining the variation request 
Change accordion text to View variation details 
**approve**
Change banner to Variation for [First name Last name] approved 
Change text under What happens next to:
The variation for [first name last name] has been approved with your digital signature. 
We have sent an email notification to the probation practitioner. 
They will be able to print and issue the licence or post sentence supervision order.
**refer-confirm**
Change banner to Variation for [First name Last name] declined
> CVSL 582 PDU head approval journey

- server/views/partials/timePicker.njk
in any hours and minute input fields
This applies to the time fields within all pages
eg /initial-meeting-time , /additional-licence-conditions
> CVSL-607 prevent user from adding more than 2 digits 

- server/middleware/fetchLicenceMiddleware.test.ts
- server/middleware/fetchLicenceMiddleware.ts
ignore teams check when accessing a licence with the ACO role. PDU head can view cases across all teams.
> ignore teams check when accessing a licence with the ACO role.

- server/views/pages/vary-approve/cases.njk
ticket: PDUH currently see the tabs 'my cases' and 'all cases in this region'. PDUHs don't work on cases so 'my cases' needs to be replaced with 'Cases in this PDU'
> CVSL-630 change tab label as PDUH's don't have cases

- helm_deploy/create-and-vary-a-licence/templates/email-probation-practioner-cronjob.yaml
- jobs/emailProbationPractioner.ts
- server/@types/licenceApiClientTypes.ts
- server/@types/licenceApiImport/index.d.ts
- server/data/licenceApiClient.test.ts
- server/data/licenceApiClient.ts
New cronjob to email the probation practitioner of any edited licences that won't be approved in time for prisoner's release. The affected licences are obtained from the cvl api and the actual emailing is also done by the same api. However all the cron jobs have been set up in the front end. The relevant api endpoints are '/edited-licences-unapproved-by-crd' and '/notify-probation-of-unapproved-licences '
> CVSL-619 - email probation practitioner cronjob

- jobs/promptLicenceCreation.ts
- server/routes/viewingLicences/handlers/viewCases.test.ts
- server/routes/viewingLicences/handlers/viewCases.ts
- server/routes/viewingLicences/index.ts
- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
- server/services/container.test.ts
- server/services/container.ts
Added a new wrapper object that acts like an array but `filter` takes an additional parameter as an exclusion reason. 
Items that are filtered out are kept in a separate array internally and passed along through maps, filters and concats so they can be inspected at the end of the pipeline. 
This is then exposed on a `/licence/view/cases-with-exclusions.json` url, which just dumps out the cases, cases that were excluded and their reason for exclusion.
All the caseload methods have been altered to use this structure as they share a lot of the same functionality but only currently exposed this for the OMU caseload
> CVSL-645 Exposing exclusion information

- server/routes/viewingLicences/handlers/viewCases.test.ts
- server/routes/viewingLicences/handlers/viewCases.ts
- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
- server/services/omuCaselist.test.ts
- server/services/omuCaselist.ts
Cases with status NOT_IN_PILOT, OOS_RECALL, OOS_BOTUS to be be moved from probation view to prison view. However they are only to be displayed if their CRD is in the future.
> CVSL-164 move out of scope cases to prison view

- jobs/promptLicenceCreation.ts
- server/services/caseloadService.test.ts
- server/services/caseloadService.ts
- server/services/prisonerService.test.ts
- server/services/prisonerService.ts
for reference 
Moment startOf('isoWeek') refers to a Monday
Date-fns weekStartsOn:1 is a Monday. Other wise default is a Sunday
moment().add(12, 'weeks').startOf('isoWeek')  returns Moment<2023-01-23T00:00:00+00:00>
startOfWeek(add(new Date(), { weeks: 12 }), { weekStartsOn: 1 })  returns 2023-01-23T00:00:00.000Z
(based on todays date of 2022-11-04)
prisonerSearchApiClient.searchPrisonersByReleaseDate() needs dates as a string like '2022-11-04'
Both   
moment('2022-11-04').format('YYYY-MM-DD') 
and 
format(new Date('2022-11-04'), 'yyyy-MM-dd') 
return string  '2022-11-04'
> CVSL-709 swap moment for date-fns

- jobs/promptLicenceCreation.ts
- jobs/promptLicenceCreationService.test.ts
- jobs/promptLicenceCreationService.ts
- package.json
1, The logic within excludeCasesNotAssignedToPpWithinPast7Days was wrong. It was thought the allocationDate referred to the date a PP was allocated. In fact the allocationDate is part of the offenderCrn object. 
A call is made to probation-offender-search to get the offender details. The returned object contains the offenderManagers array exampled below. The relevant data from the offenderManagers array is in bold. 
"offenderManagers": [
{
"staff": {
"code": "A123456B",
"forenames": "some",
"surname": "practioner"
},
"partitionArea": "National Data",
"softDeleted": false,
"team": {
"code": "someTeamCode",
"description": "Durham & Darlington IOM",
"district": {
"code": "someDistrictCode",
"description": "Durham"
},
"borough": {
"code": "someBoroughCode",
"description": "County Durham and …
> CVSL 709 refactor for tests

- jobs/promptLicenceCreation.ts
- server/services/communityService.ts
- server/services/prisonerService.ts
The apis were throwing exceptions because too much data was passed in one go.  This was preventing promptLicenceCreation cronjob from completing.  Args chunked to 500.
app insights:
prison-api
probation-offender-search
> CVSL-730 chunk args passed in api calls

- server/routes/varyingLicences/index.ts
- server/utils/nunjucksSetup.test.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/create/checkAnswers.test.ts
- server/views/pages/vary/timeline.test.ts
- server/views/partials/licenceDetailsBanner.njk
The date in header when displaying offender records is different for vary journey pages. 
**Jira ticket:**
> CVSL-732 displays correct date and description for vary journey

- server/views/pages/create/initialMeetingPerson.njk
AC: Implement the code in the ticket to make it easier for users of speech recognition software to navigate the page
Could have removed the H1 altogether and retained the govukInput nunjucks component and set isPageHeader to true. However there is an govukWarningText component (only displays if dates aren't compatible) that then wouldn't render in the correct place. It would sit above the H1. So have changed from using nunjucks component to straight HTML. 
**Retaining the nunjucks component would have presented like this**
**instead of**
> CVSL-639 make input accessibility compliant

- server/views/partials/header.njk
In the service header, make the alt attribute of the logo “null” and put a non-breaking space after “HMPPS”.
> CVSL-637 fix accessibility issue

- assets/sass/components/_header-bar.scss
- server/views/partials/header.njk
Becomes black on click for accessibility colour contrast and underline on hover, like other services.
> CVSL-640 CSS for signout link. 

- server/listeners/eventHandlers/probationEvents/index.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.ts
To help identify the reasons why the change offender event is sometimes failing
> CVSL-751 logs added

- jobs/updateLicences.ts
- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.test.ts
- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.ts
Changing licence activation check to use the ARD on the licence rather than confirmedReleaseDate in NOMIS
Explanation:
When an offender has an IS91 warrant as their primary conviction (resulting in the legalStatus being `IMMIGRATION_DETAINEE`), the confirmedReleaseDate in NOMIS will always be `NULL`. As such, we need to use the actualReleaseDate/ARD that's stored (and preserved) on the licence.
Also changing datesChangedEventHandler to use legalStatus rather than imprisonmentStatus for consistency, and to cover very rare edge cases.
> Changing confirmedReleaseDate from prisoner profile to ARD on the licence

- server/views/pages/create/additionalLicenceConditionInput.njk
Fixing some unexpected behaviour where 'undefined' was being added to urls when trying to delete an additional condition from its input page.
> Fixing url generation bug for additional condition input delete button

- server/routes/support/handlers/offenderAudit.ts
- server/services/licenceService.test.ts
- server/services/licenceService.ts
Replace moment with date-fns and use the correct date format specified in the API schema. The correct date format for use with the CVL API is 'dd/MM/yyyy HH:mm:ss'
> refs cvsl-768

- server/data/licenceApiClient.test.ts
- server/data/licenceApiClient.ts
- server/routes/support/handlers/offenderLicenceStatus.test.ts
- server/routes/support/handlers/offenderLicenceStatus.ts
- server/services/licenceOverrideService.test.ts
- server/services/licenceOverrideService.ts
Fixes issue where CVL-staff usernames were not visible in the audit log when overriding a licence status.
> CVSL-820 - Adding username to API call when overriding licence status so it's visible in the audit log

- server/data/licenceApiClient.test.ts
- server/data/licenceApiClient.ts
- server/routes/support/handlers/offenderLicenceStatus.test.ts
- server/routes/support/handlers/offenderLicenceStatus.ts
- server/services/licenceOverrideService.test.ts
- server/services/licenceOverrideService.ts
Reverts ministryofjustice/create-and-vary-a-licence#494
Unfortunately the changes made in CVSL-820 didn't have the intended effect, and with more pressing issues that need fixing, it seems best to remove the code for now (to make sure current functionality is not impacted) and fix it at a later date.
> Revert "CVSL-820 - Adding username to API call when overriding licence status so it's visible in the audit log"

- cypress.config.ts
- integration_tests/integration/eventHandlers.cy.ts
- integration_tests/mockApis/community.ts
- server/@types/communityClientTypes.ts
- server/data/communityApiClient.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.test.ts
- server/listeners/eventHandlers/probationEvents/offenderManagerChangedEventHandler.ts
- server/services/communityService.ts
The `OFFENDER_MANAGER_CHANGED` event handler is failing due to outdated data being returned by the Probation Offender Search API. From speaking to the Delius team, the long-term plan is to create a new API bespoke for CVL, but for the interim period, the Search API call is being swapped for a slower Community API call that will return the correct data instantly.
> CVSL-720 - Swapping probation search for Community API

- server/applicationVersion.ts
- server/config.ts
- server/middleware/setUpStaticResources.ts
- server/middleware/setUpWebSecurity.ts
- server/utils/nunjucksSetup.ts
Currently the assets are only set to cache for 20 seconds. This should drastically reduce the number of requests to the server and also make browsing logs easier to see.
In production the css cache will be linked to the deployment version rather than pod start up time - currently the browser caches a version for each pod
There's also another little Helmet/CSP fix copied across from the template project to prevent user's being stuck on a page if they submit a page and the app detects their session has timed out. 
Previously CSP would have kicked in and an error would have been presented in terminal and the user would be stranded. Now the user will be redirected to auth.
> CVSL-1022 Add better caching of assets

- README.md
- docker-compose.yml
- run-local.sh
This PR takes the previous work around automation done on the API one step further and creates two local scripts which can be used to build front and back end containers and run the respective services. This includes the script needed to build and run the UI service along with changes to `docker-compose.yml` file to accommodate health checks and an update to the README.
> FB split script in two one for ui and one for API

- run-local.sh
- server/routes/creatingLicences/handlers/caseload.test.ts
- server/routes/creatingLicences/handlers/caseload.ts
- server/routes/creatingLicences/handlers/checkAnswers.test.ts
- server/routes/creatingLicences/handlers/checkAnswers.ts
- server/routes/creatingLicences/handlers/confirmCreate.test.ts
- server/routes/creatingLicences/handlers/confirmCreate.ts
- server/routes/creatingLicences/handlers/confirmation.test.ts
- server/routes/creatingLicences/handlers/confirmation.ts
- server/routes/creatingLicences/index.ts
- server/routes/varyingLicences/handlers/confirmDiscardVariation.test.ts
- server/routes/varyingLicences/handlers/confirmDiscardVariation.ts
- server/routes/varyingLicences/handlers/confirmation.test.ts
- server/routes/varyingLicences/handlers/confirmation.ts
- server/views/pages/create/checkAnswers.njk
Currently the "return to caseload" links rely on storing the destination location in the session.
When the application session times out the user will be redirected to auth and assuming the user's auth session is still active they will be redirected back to the application where a new application session will be created. 
This happens transparently and the user will returned to the page where they were on.
The lack of a return destination in the session breaks the session.
This change puts in a sensible default location for each link. (Might be nicer to move to a central middleware or better different paths for each destination - which would massively improve observability but that would require quite a lot of restructuring)
> CVSL-1143 fixing return to caseload links

- audit-ci.json
Added allowlist to `audit-ci.json` to cease alerts for the following dependencies which we don't need to fix for now:
`request` pulls through a vulnerability to the `uk-bank-holidays` package and there is no fix available - in the future we'll need to add our own functionality rather than importing the `uk-bank-holidays` package. 
`tough-cookie` pulls through a vulnerability to cypress but as this is being used in development it poses a low risk and we deem it not worth fixing for now. 
```request  *
Severity: moderate
Server-Side Request Forgery in Request - https://github.com/advisories/GHSA-p8p7-x288-28g6
Depends on vulnerable versions of tough-cookie
No fix available
node_modules/request
request-promise  >=0.0.2
Depends on vulnerable versions of request
node_modules/request-promise …
```
> CVSL-1185 add allowlist to audit-ci file to stop false positive security alerts

- server/routes/manageConditions/handlers/additionalLicenceConditionInput.test.ts
- server/routes/manageConditions/handlers/additionalLicenceConditionInput.ts
- server/routes/manageConditions/handlers/additionalLicenceConditionUploadInput.test.ts
- server/routes/manageConditions/handlers/additionalLicenceConditionUploadInput.ts
- server/routes/manageConditions/index.ts
- server/utils/conditionRoutes.ts
- server/views/pages/create/additionalLicenceConditionMapInput.njk
Split out the existing routes so MEZ has its own template on
`/additional-licence-conditions/condition/:conditionId`
and then that template posts to its own special handlers for setting data and deletions:
```
/additional-licence-conditions/condition/:conditionId/file-upload-input
/additional-licence-conditions/condition/:conditionId/file-upload-removal
``` 
This reduces complexity in normal condition endpoints and also allows the ability to customize the MEZ journey a bit more freely
> CVSL-1287 Splitting out MEZ and normal condition templates

- helm_deploy/create-and-vary-a-licence/Chart.yaml
To cope with upcoming deprecations:
```
W1004 13:08:34.198901     347 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
````
> CVSL-1411 updating helm charts

- helm_deploy/create-and-vary-a-licence/Chart.yaml
- helm_deploy/create-and-vary-a-licence/values.yaml
This PR migrates the project to use groups of IPs in their allowlist.
By referring to groups to IP addresses, we can centralize the definition of groups of ip addresses.
If these lists require changing in the future, we can change the definition once and future deploys across all services will automatically include these new IPs.
1 allowlist(s) have been detected that can be migrated.
The effect of applying this PR is as follows:
- The following groups will be applied: `internal,prisons,private_prisons`
- The size of the allowlist defined in this file will change: `45 => 2 (43 removed)`
The new Group membership will result in the following IPs being added to your allowlist by applying this PR:
- sodexo1 (80.86.46.16/32)
- sodexo2 (80.86.46.17/32)
- sodexo3 (80.86.46.18/32)
- …
> Migrating project to use groups in allowlist

- server/middleware/setUpWebSession.ts
This is to help counter any issues with other cookies on the domain overriding our sessions
> CVSL-1513: Adding unique name for session cookie

- helm_deploy/create-and-vary-a-licence/templates/expire-active-licences-cronjob.yaml
- helm_deploy/create-and-vary-a-licence/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-test1.yaml
- helm_deploy/values-test2.yaml
Disabled in dev and test environments because the dates of these cases are often unreliable, so could lead to mass-deactivation of useful test cases.
> CVSL-1514 Moving cronjob values to new pattern and enabling in preprod and prod

- server/routes/creatingLicences/handlers/checkAnswers.test.ts
- server/routes/creatingLicences/handlers/checkAnswers.ts
- server/routes/initialAppointment/handlers/initialMeetingContact.test.ts
- server/routes/initialAppointment/handlers/initialMeetingContact.ts
- server/routes/initialAppointment/handlers/initialMeetingName.test.ts
- server/routes/initialAppointment/handlers/initialMeetingName.ts
- server/routes/initialAppointment/handlers/initialMeetingPlace.test.ts
- server/routes/initialAppointment/handlers/initialMeetingPlace.ts
- server/routes/initialAppointment/handlers/initialMeetingTime.test.ts
- server/routes/initialAppointment/handlers/initialMeetingTime.ts
- server/routes/initialAppointment/handlers/initialMeetingUpdatedFlashMessage.test.ts
- server/routes/initialAppointment/handlers/initialMeetingUpdatedFlashMessage.ts
- server/routes/viewingLicences/handlers/viewLicence.test.ts
- server/routes/viewingLicences/handlers/viewLicence.ts
- server/utils/urlAccessByStatus.test.ts
- server/utils/urlAccessByStatus.ts
- server/views/pages/create/checkAnswers.njk
- server/views/pages/create/checkAnswers.test.ts
- server/views/pages/view/view.njk
Also adds flash messages to initial appointment updates for SUBMITTED and APPROVED licences
> CVSL-1587 Adding initial appointment editing without reapproval

- server/middleware/populateCurrentUser.test.ts
- server/middleware/populateCurrentUser.ts
This provides access to the serviceto people who have unverified email addresses. Reasoning that it's better to not store an unverified email address
> CVSL-1767 Allow prison users to not have email

- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.ts
- server/routes/approvingLicences/handlers/approvalCases.ts
- server/routes/approvingVariations/handlers/varyApproveList.ts
- server/routes/viewingLicences/handlers/viewCases.ts
- server/routes/viewingLicences/handlers/viewLicence.ts
- server/routes/views/CaseloadViewModel.test.ts
- server/services/caseloadService.ts
- server/services/licenceService.test.ts
- server/services/prisonerService.ts
- server/utils/nunjucksSetup.ts
- server/utils/utils.test.ts
- server/utils/utils.ts
- server/views/pages/view/cases.njk
- server/views/partials/viewCases.njk
Added 3 helper functions for parsing dates and moved over existing code to use them:
* `parseIsoDate` => `2023-01-23`
* `parseCvlDate` => `23/01/2023`
* `parseCvlDateTime` 
* `{ withSeconds: true }`  => `23/01/2023 13:45:50`
* `{ withSeconds: false }`  => `23/01/2023 13:45`
> CVSL-1786 Adding standard parsing methods for dates

- server/routes/creatingLicences/handlers/confirmation.test.ts
- server/routes/creatingLicences/handlers/confirmation.ts
This PR addresses a bug where when a hard stop licence was created, the `Return to caselist` button did not work. This now redirects to the view caseload on clicking of the button rather than the create caseload when a hard stop licence is created and submitted.
> CVSL-1842 adjust logic for backlink

- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.test.ts
- server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.ts
This PR is to process PRRD data changes when sentence dates are updated following an event in the front end.
> CVSL-1771 add functionality to update PPRD on sentence date update

- server/routes/varyingLicences/handlers/policyChangesNotice.test.ts
- server/routes/varyingLicences/handlers/policyChangesNotice.ts
Fixing a small bug that's been around for a while.
When a user has already reviewed all policy changes, they still meet the criteria of being a `VARIATION_IN_PROGRESS` with a parent on an older version. If the user doesn't submit the variation immediately, every time they go to edit the variation, they are presented with a screen telling them that there are "Zero policy changes to review"
This screen is redundant for these users, so should just be skipped.
> CVSL-2084 Preventing policy upgrade notice page from appearing when there are zero changes to review

- server/middleware/populateCurrentUser.test.ts
- server/middleware/populateCurrentUser.ts
This is based on the logic in the community api which triggers the 404 response we receive when trying to request one of these teams [here](https://github.com/ministryofjustice/community-api/blob/5a30ec4bab1fc648cf14201972dbe3ad9ca583df/src/main/java/uk/gov/justice/digital/delius/jpa/standard/repository/TeamRepository.java#L15).
> CVSL-2108 Filtering out inactive teams

- helm_deploy/create-and-vary-a-licence/values.yaml
- server/config.ts
- server/utils/nunjucksSetup.ts
- server/views/pages/accessDenied.njk
- server/views/pages/accessDenied.test.ts
- server/views/pages/error.njk
- server/views/pages/error.test.ts
This PR is to add the self report URL to our error pages which provides a direct link to ServiceNow when a user encounters a 401 or 500 error. 
Delius user with a 500 error:
Nomis user with a 401 error
> CVSL-2113 add self report url to error pages

- server/config/policyChangeHintText.ts
Changes were made to the outOfBoundsPremises condition in v2.1 of the policy some time ago, which results in it being recognised as `NEW_OPTIONS` change when going through a policy upgrade.
While this hasn't been raised so far, with the new version of the policy anyone upgrading from v1.0 to v2.0 to v3 would experience the issue of missing content.
> CVSL-2192 Adding missing policy upgrade hint text for outOfBoundsPremises condition

- server/views/pages/licence/HDC_AP.njk
- server/views/pages/licence/HDC_AP.test.ts
Updated the CVL API to include homeDetentionCurfewActualDate on a licence so now updated the template to show this value where needed.
> CVSL-2145 add hdcad to hdc licence template

- server/routes/creatingLicences/handlers/confirmation.ts
- server/views/pages/create/confirmation.njk
- server/views/pages/create/confirmation.test.ts
This PR is content change for the confirmation page based on the licence kind being HDC.
> CVSL-2336 add logic to change confirmation message based on kind

- server/views/partials/hdc/hdcInitialMeetingTimeInputs.njk
- server/views/partials/initialMeetingTimeInputs.njk
This follow on PR is based on demo feedback to combine the fields into a single fields for date and time instead of having two separate fieldsets.
> CVSL-2329 combine time and date into a single fieldset

- server/views/pages/view/cases.njk
- server/views/pages/view/cases.test.ts
This follow on PR adds the HDC release label to cases in the CA view, where the person is on probation.
> CVSL-2337 add HDC highlight for cases in the people on probation tab

- server/routes/initialAppointment/handlers/hardStop/index.ts
- server/routes/viewingLicences/handlers/viewLicence.test.ts
- server/routes/viewingLicences/handlers/viewLicence.ts
- server/routes/viewingLicences/index.ts
- server/views/pages/view/view.njk
- server/views/pages/view/view.test.ts
This PR is to add the HDC licence data summary to the CA view. This adds details on curfew address, first night curfew details and curfew hours where a HDC licence has been submitted or approved. 
Submitted - CA - View the licence:
Approved - CA - Print the licence:
> CVSL-2338 add HDC licence data summary when viewing or printing a licence in CA view

- server/routes/varyingLicences/handlers/timeline.test.ts
- server/routes/varyingLicences/handlers/timeline.ts
- server/views/pages/vary/timeline.njk
- server/views/pages/vary/timeline.test.ts
- server/views/pages/vary/viewActive.njk
- server/views/pages/vary/viewActive.test.ts
- server/views/partials/varyCallToActions.njk
This PR is to make content changes for the vary screens once a HDC licence is active. It includes changes to buttons and removing vary functionality (i.e. the buttons) when a licence is viewed. A new component explaining how to vary a HDC licence is also included.
> CVSL-2344 content changes to the vary view for HDC licences

- server/routes/varyingLicences/handlers/viewActiveLicence.test.ts
- server/routes/varyingLicences/handlers/viewActiveLicence.ts
- server/routes/varyingLicences/index.ts
- server/views/pages/vary/viewActive.njk
- server/views/pages/vary/viewActive.test.ts
This PR is to add the HDC curfew summary when a PP is viewing a HDC licence in the vary journey.
> CVSL-2345 add HDC curfew summary when viewing a licence in the vary journey

- server/routes/varyingLicences/handlers/caseload.test.ts
- server/routes/varyingLicences/handlers/caseload.ts
- server/views/pages/vary/caseload.njk
- server/views/pages/vary/caseload.test.ts
This PR is to add a HDC marker to HDC licences in the vary caseload view.
> CVSL-2346 add HDC release marker for vary caseload

- server/views/pages/search/probationSearch/probationSearch.njk
- server/views/pages/search/probationSearch/probationSearch.test.ts
This follow on PR adds the HDC release marker for search, both on the people in prison and people on probation tabs.
> CVSL-2346 add HDC release marker for PP search

- README.md
- integration_tests/integration/createHdcLicence.cy.ts
- server/middleware/preLicenceCreationMiddleware.test.ts
- server/middleware/preLicenceCreationMiddleware.ts
- server/routes/creatingLicences/crdLicenceInHardStop.test.ts
- server/routes/creatingLicences/handlers/hdc/index.ts
- server/routes/creatingLicences/index.ts
This PR is to address bug found during HDC integration testing. This bug allowed any COM to create a HDC licence for any eligible prisoner. We are now checking whether the COM attempting to create the licence (CRD or HDC) has a relationship to the person the licence is being created for (either as their responsible COM or part of the same team).
> CVSL-2591 add pre licence creation middleware

- integration_tests/integration/approveLicence.cy.ts
- integration_tests/mockApis/licence.ts
- server/@types/licenceApiImport/index.d.ts
- server/routes/approvingLicences/handlers/approvalView.test.ts
- server/routes/creatingLicences/handlers/checkAnswers.test.ts
- server/routes/varyingLicences/handlers/viewActiveLicence.test.ts
- server/routes/viewingLicences/handlers/printLicence.test.ts
- server/routes/viewingLicences/handlers/viewLicence.test.ts
- server/services/hdcService.test.ts
- server/views/pages/licence/HDC_AP.njk
- server/views/pages/licence/HDC_AP_PSS.njk
- server/views/pages/licence/partials/hdcCurfewTimes.njk
This PR is to adjust the macro which populates the curfew address having changed the representation of curfew addresses in the backend. This is to match what will be from the HDC API for curfew addresses.
> CVSL-2596 adjust macro to include county and adjust names of variables

- server/views/pages/approve/cases.njk
- server/views/pages/approve/keyDates.njk
- server/views/pages/create/caseload.njk
- server/views/pages/search/probationSearch/probationSearch.njk
- server/views/pages/vary/caseload.njk
- server/views/partials/viewCases.njk
This PR is to fix a bug where the Early marker was being shown instead of the HDC marker. Adjusted now the HDC marker takes precedence.
> CVSL-2729 adjust ordering of marker display

- server/views/pages/create/confirmation.njk
- server/views/pages/create/confirmation.test.ts
This PR is to update content on the confirmation screen once a HDC licence has been created.
**Before**
**After**
> CVSL-2536 update content

- integration_tests/integration/caSearch.cy.ts
- integration_tests/pages/caSearch.ts
- server/routes/search/handlers/caSearch.test.ts
- server/routes/search/handlers/caSearch.ts
- server/views/pages/search/caSearch/caSearch.njk
- server/views/pages/search/caSearch/caSearch.test.ts
This PR is to introduce the tabs for the CA search so that results can be split into people in prison and people on probation. This PR provides the empty states for both tabs should no search results be returned.
> CVSL-2912 add tabs and empty states for CA search

- server/views/pages/licence/AP.njk
- server/views/pages/licence/AP.test.ts
Based on the change of requirement to the ticket, this PR is to remove the paragraph entirely and not replace it with anything. 
**Before**
**After**
> CVSL-3225 change content for AP licence

- server/views/partials/hardStop/releasesInTwoWorkingDaysTab.njk
This PR is to remove a paragraph from the CA view which mentions the early release scheme. 
Before
After
> CVSL-3345 remove paragraph
