README.md
docker-compose-test.yml
docker-compose.yml
integration_tests/pages/index.js
server/routes/index.test.ts
server/views/pages/index.njk

Move README.md away from typescript template and more descriptive for this service.
Add more container dependencies into docker-compose.yml  (local DB image)
Alter landing page & tests

Alter readme, docker-compose, landing page content and tests for it.

---

assets/js/card.js
assets/sass/application.sass
assets/sass/components/_card.scss
integration_tests/pages/index.js
run-full.sh
server/routes/index.test.ts
server/views/pages/index.njk
server/views/partials/card.njk

Adds ability for a tiled home landing page.
Example top-level workflows added.

CVL-16: Add home page tiles for various top-level workflows

---

server/data/communityApiClient.test.ts
server/data/communityApiClient.ts
server/routes/otherRoutes.ts
server/services/communityService.ts
server/views/pages/prisonerDetail.njk
server/views/pages/staffDetail.njk

Another quick one - minor updates to make staff details endpoint work too.

CVL-28: Fixes for the community API to finish off.

---

server/data/restClient.ts

CVL-9: Fix for image stream error crashing pods

---

helm_deploy/create-and-vary-a-licence/values.yaml

Correcting attribute names to match generic service expectations.

CVL-2 to fix Gotenberg deployment as a generic service

---

package-lock.json
package.json

Fixes npm security audit issue

CVSL-44: Update dependency path-parse to fix security vulnerability

---

package-lock.json
package.json
server/config/conditions.ts
server/middleware/validationMiddleware.test.ts
server/middleware/validationMiddleware.ts
server/routes/creatingLicences/handlers/additionalConditions.test.ts
server/routes/creatingLicences/handlers/additionalConditions.ts
server/routes/creatingLicences/index.ts
server/routes/creatingLicences/types/additionalConditions.ts
server/routes/creatingLicences/types/regionOfResidence.ts
server/utils/conditionsProvider.test.ts
server/utils/conditionsProvider.ts
server/views/formBuilder.njk
server/views/formBuilder.test.ts
server/views/pages/create/additionalConditions.njk
server/views/pages/create/additionalConditions.test.ts
server/views/partials/additionalConditionsInputs/placeOfResidence.njk

- Licence conditions in JSON
- conditionsProvider util functions to provide the conditions in various structures (e.g. grouped by group name)
- formBuilder which takes the names of partials as params to decide which partials to display
- AdditionalConditions form validation - this will probably change in future if split out into separate pages

CVSL-107: Add additional conditions config and form builders + validation

---

server/enumeration/yesOrNo.ts
server/routes/creatingLicences/handlers/additionalConditionsQuestion.test.ts
server/routes/creatingLicences/handlers/additionalConditionsQuestion.ts
server/routes/creatingLicences/handlers/bespokeConditionsQuestion.test.ts
server/routes/creatingLicences/handlers/bespokeConditionsQuestion.ts
server/routes/creatingLicences/types/yesOrNo.ts
server/views/pages/create/additionalConditionsQuestion.njk
server/views/pages/create/bespokeConditionsQuestion.njk

* Added enum for YES/NO
* Removed hardcoded offender data, replaced with licence data from session

CVSL-104 & CVSL-108: Completed yes/no question pages, pulling licence data from session

---

.circleci/config.yml
logger.ts
server/utils/nunjucksSetup.ts

Fixes two things:
* Updates the orb to major version 3.11  (contains a trivy scan failure fix)
* Updates the service name to lowercase in title.

CVSL-148: Updated orb (trivy scan failure) and title of service to lowecase

---

assets/sass/components/_licence.scss
server/routes/viewingLicences/handlers/printLicence.test.ts
server/routes/viewingLicences/handlers/printLicence.ts
server/views/pages/licence/AP.njk
server/views/pages/licence/AP_PSS.njk
server/views/pages/licence/PSS.njk
server/views/pages/licence/partials/induction.njk
server/views/pages/licence/partials/signatures.njk
server/views/pages/licence/partials/title.njk

CVSL-186: Updates from review comments.

---

integration_tests/integration/createLicence.spec.ts
integration_tests/mockApis/licence.ts
integration_tests/pages/additionalConditionInput.ts
server/config/conditions.ts
server/routes/creatingLicences/types/additionalConditionInputs/curfewAddress.ts
server/routes/creatingLicences/types/additionalConditionInputs/namedIndividuals.ts
server/routes/creatingLicences/types/additionalConditionInputs/namedOrganisation.ts
server/routes/creatingLicences/types/additionalConditionInputs/noContactWithVictim.ts
server/routes/creatingLicences/types/additionalConditionInputs/reportToStaff.ts
server/routes/creatingLicences/types/additionalConditionInputs/specifiedItem.ts
server/routes/creatingLicences/types/additionalConditionInputs/unsupervisedContact.ts
server/services/licenceService.ts
server/transformers/removeEmptyArrayItems.test.ts
server/transformers/removeEmptyArrayItems.ts
server/utils/conditionsProvider.ts
server/utils/nunjucksSetup.ts
server/views/formBuilder.njk
server/views/formBuilder.test.ts
server/views/pages/create/bespokeConditions.njk
server/views/pages/create/bespokeConditions.test.ts
server/views/pages/create/checkAnswers.test.ts
server/views/pages/create/initialMeetingTime.njk
server/views/pages/view/view.test.ts
server/views/partials/additionalConditionsSummary.njk
server/views/partials/datePicker.njk
server/views/partials/timePicker.njk
server/views/partials/timePicker.test.ts

- Adding remaining conditions
- Transformer function to remove empty strings from array inputs (i.e. empty 'Add another' fields)
- Re-jigged how form values are populated on formBuilder

CVSL-184: Form builder option for "Add another" button

---

integration_tests/integration/createLicence.spec.ts
integration_tests/pages/additionalConditionInput.ts
server/config/conditions.ts
server/enumeration/inputTypes.ts
server/routes/creatingLicences/types/additionalConditionInputs/appointmentTimeAndPlace.ts
server/routes/creatingLicences/types/additionalConditionInputs/behaviourProblems.ts
server/routes/creatingLicences/types/additionalConditionInputs/drugTestLocation.ts
server/routes/creatingLicences/types/additionalConditionInputs/electronicMonitoringTypes.ts
server/routes/creatingLicences/types/additionalConditionInputs/medicalAppointmentType.ts
server/routes/creatingLicences/types/additionalConditionInputs/outOfBoundsPremises.ts
server/routes/creatingLicences/types/additionalConditionInputs/regionOfResidence.ts
server/routes/creatingLicences/types/additionalConditionInputs/restrictionOfResidency.ts
server/routes/creatingLicences/types/additionalConditionInputs/unsupervisedContact.ts
server/routes/creatingLicences/types/additionalConditionInputs/workingWithChildren.ts
server/routes/creatingLicences/types/address.ts
server/routes/creatingLicences/types/date.ts
server/routes/creatingLicences/types/time.ts
server/utils/conditionsProviderExpand.test.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/validators/decorators.ts
server/validators/simpleTimeValidator.test.ts
server/validators/simpleTimeValidator.ts
server/views/formBuilder.njk
server/views/formBuilder.test.ts
server/views/partials/timePicker.njk
server/views/partials/timePicker.test.ts

- Added two decorators : 
- One is @IsOptional() which checks the object, if its empty it will pass, if its not empty, it will get validated
- The other is @Either() which takes the name of another field. The annotated field will get validated if the other named field is empty, or the annotated field itself has some data entered
- Changed the timePicker to default the AM/PM field to empty which forces the user to pick a value, and also allows us to determine if data has been entered in the field apart from AM/PM
- Added the dropdown picker

CVSL-187: Add dropdown field type and update validation messages

---

server/views/pages/licence/AP.njk
server/views/pages/licence/AP_PSS.njk
server/views/pages/licence/PSS.njk
server/views/pages/licence/partials/signatures.njk

* Remove date for signature of the person leaving prison.
* Alter `Signed by` to `Approved by`- the person who approved.

CVSL-223: Minor updates to signatures.

---

server/config/conditions.ts
server/utils/conditionsProvider.ts
server/utils/conditionsProviderExpand.test.ts

5 of the additional conditions include additional text to make sentences make sense when optional values are either present or omitted. This PR deals with those by using `.includeBefore` fixed text which is prepended to the value when it is present, or omitted when the value is not present.

CVSL-215: Expanding the trixy conditions that alter the sentence text.

---

server/utils/conditionsProvider.ts

Null check on rules.case - avoid undefined for conditions.

CVSL-231: Fix case rule bug

---

server/routes/creatingLicences/types/additionalConditionInputs/reportToApprovedPremises.ts
server/routes/creatingLicences/types/additionalConditionInputs/reportToPoliceStation.ts

- Noticed in dev review this morning that these validation messages don't make sense for fields which no longer support "Add Another" list type

CVSL-184: Change validation message for 2 inputs

---

assets/sass/components/_licence.scss
helm_deploy/create-and-vary-a-licence/values.yaml
helm_deploy/values-dev.yaml
server/config.ts
server/config/conditions.ts
server/routes/creatingLicences/types/additionalConditionInputs/electronicMonitoringPeriod.ts
server/routes/viewingLicences/handlers/printLicence.test.ts
server/routes/viewingLicences/handlers/printLicence.ts
server/views/pages/approve/cases.njk
server/views/pages/create/caseload.njk
server/views/pages/index.njk
server/views/pages/licence/pdf-layout.njk
server/views/pages/view/cases.njk

Example of the generated PDF with watermark
[WATERMARK.pdf](https://github.com/ministryofjustice/create-and-vary-a-licence/files/7584482/WATERMARK.pdf)

CVSL-245: Content changes for private beta + pdf watermark in dev

---

server/config/conditions.ts
server/utils/conditionsProvider.ts
server/utils/conditionsProviderExpand.test.ts

- Recursively expand nested inputs (i.e. conditional reveal inputs underneath radio buttons) into the condition

CVLS-249: Expand conditional reveal licence condition data

---

.codecov.yml
helm_deploy/create-and-vary-a-licence/templates/activate-licences-cronjob.yaml
jobs/activateLicences.ts
server/data/licenceApiClient.ts
server/services/licenceService.ts
server/utils/azureAppInsights.ts

- k8s cronjob to update the status to ACTIVE, any licences which are APPROVED and within the licence period
- also disabled the codecov comment

CVSL-174: Add job to activate approved licences

---

helm_deploy/create-and-vary-a-licence/Chart.yaml
helm_deploy/create-and-vary-a-licence/templates/activate-licences-cronjob.yaml

- Upgrade `generic-service` and `generic-prometheus-alerts`

CVSL-174: Helm deploy fix for cronjob

---

server/routes/creatingLicences/types/additionalConditionInputs/alcoholMonitoringPeriod.ts
server/routes/creatingLicences/types/additionalConditionInputs/electronicMonitoringPeriod.ts

Fixes bug reported in CVSL-252 - the date entered is between the CRD and LED.

CVSL-252: Added validation for date between CRD and LED.

---

integration_tests/integration/createLicence.spec.ts
integration_tests/integration/editLicence.spec.ts
integration_tests/mockApis/licence.ts
integration_tests/pages/caseload.ts
integration_tests/pages/checkAnswers.ts
integration_tests/pages/editLicenceQuestion.ts
integration_tests/plugins/index.ts
server/routes/creatingLicences/handlers/editQuestion.test.ts
server/routes/creatingLicences/handlers/editQuestion.ts
server/routes/creatingLicences/index.ts
server/views/pages/create/checkAnswers.njk
server/views/pages/create/checkAnswers.test.ts
server/views/pages/create/editQuestion.njk

CVSL-137: Edit licence journey

---

integration_tests/integration/createLicence.spec.ts
integration_tests/pages/additionalConditionInput.ts
server/config/conditions.ts
server/utils/conditionsProviderExpand.test.ts

CVSL-278: Replace dropdown for radio button

---

server/services/communityService.test.ts
server/services/prisonRegisterService.test.ts
server/services/prisonerService.test.ts
server/services/prisonerService.ts
server/views/pages/view/view.njk

Details of coverage changes here https://app.codecov.io/gh/ministryofjustice/create-and-vary-a-licence/compare/main...cvsl-266-service-layer-test-coverage/changes
* 3 services now with 100% coverage
* Coverage of licenceService still to come in another PR

CVSL-266: Service layer test coverage

---

server/services/licenceService.test.ts
server/services/licenceService.ts

This PR gives the LicenceService 100% test coverage and boosts the overall project coverage by ~5%

CVSL-266: Create licence tests

---

integration_tests/integration/viewAndPrintLicence.spec.ts
integration_tests/mockApis/licence.ts
integration_tests/pages/comDetails.ts
integration_tests/pages/viewCases.ts
server/routes/viewingLicences/handlers/comDetails.test.ts
server/routes/viewingLicences/handlers/comDetails.ts
server/routes/viewingLicences/index.ts
server/views/pages/view/cases.njk
server/views/pages/view/comDetails.njk

CVSL-274: Add COM details page

---

assets/sass/components/_file_upload.scss
server/validators/isValidExclusionZoneFile.test.ts
server/views/pages/approve/view.njk
server/views/pages/create/checkAnswers.njk
server/views/pages/view/view.njk
server/views/partials/additionalLicenceConditionsSummary.njk

Contains:
* Updates for view a licences /check your answers to use full-width column for displaying licence details.
* Updates for word-wrap on exclusion zone text
* New tests for the validators on the exclusion zone 'OutOfBoundRegion' class.

CVSL-304 exclusion zone tests and styling tweaks

---

server/views/layout.njk

Undefined reference to user object. 
My fault - values were not wrapped in nunjucks curly braces.

CVSL-305: Fix for pushing user details to GTM data layer

---

server/views/formBuilder.njk
server/views/formBuilder.test.ts
server/views/pages/create/additionalLicenceConditionInput.njk
server/views/pages/create/additionalPssConditionInput.njk

Small change to pass through formBuilder, add link and update view context for tests.

CVSL-347: Added CSRF token to the remove upload link.

---

assets/sass/components/_utils.scss
server/routes/creatingLicences/handlers/caseload.test.ts
server/routes/creatingLicences/handlers/caseload.ts
server/utils/nunjucksSetup.ts
server/views/pages/create/caseload.njk
server/views/pages/create/caseload.test.ts

Makes use of the MoJ sortable table component https://design-patterns.service.justice.gov.uk/components/sortable-table/

CVSL-309: Add sort functionality to the COM create caseload

---

.circleci/config.yml
helm_deploy/values-prod.yaml

* CircleCI build pipeline to promote to prod.
* `values-prod.yaml` config

CVSL-376 prod helm values

---

helm_deploy/create-and-vary-a-licence/values.yaml

https://gotenberg.dev/docs/modules/api#health

CVSL-441: Fix gotenberg health check

---

server/@types/licenceApiImport/index.d.ts
server/config.ts
server/services/caseloadService.test.ts
server/services/caseloadService.ts
server/views/pages/create/checkAnswers.njk
server/views/pages/rollout-status.njk

* CVSL-444: Record digital signature of variation approver
* CVSL-452: Restrict caseload to CRDs after 18th April
* CVSL-445: Add print button to COM view for approved licences
* CVSL-453: Update rollout status page due to delay in live date

CVSL-452-444-445-453: Various Changes

---

docker-compose-dev.yml
docker-compose-test.yml
docker-compose.yml
server/routes/home/handlers/about.ts
server/routes/home/handlers/contactUs.ts
server/routes/home/index.ts
server/views/layout.njk
server/views/pages/about.njk
server/views/pages/contactUs.njk

Also fixes health endpoint for docker-compose Gotenberg container.

CVSL-443: Contact and about us pages

---

package-lock.json

I ran through both create and vary journeys to check this as not altered behaviour.

CVSL-467: Updated version of minimist to fix security vulnerabilities

---

Dockerfile
integration_tests/index.d.ts

See template change here https://github.com/ministryofjustice/hmpps-template-typescript/pull/74

CVSL-471: Fix docker cacheing

---

server/views/layout.njk

* Two properties had changed name but not updated in the layout.njk where data is pushed to GA.

CVSL-478: Correcting the names of user properties for GA

---

integration_tests/mockApis/prisonerSearch.ts
server/services/caseloadService.ts

- by filtering to only those cases leaving within 13 weeks

CVSL-496: Reduce number of offenders searched in delius from OMU caseview

---

server/services/caseloadService.test.ts
server/services/caseloadService.ts

CVSL-513: Re-add rule to check if CRD exists, removed in error

---

.circleci/config.yml
package-lock.json
package.json

* Update circle ORB to v3.14 (fix file name for Veracode scan)
* Update minor dependencies

CVSL-521: Updating circle ORB and dependencies - to fix overnight jobs.

---

integration_tests/mockApis/community.ts
integration_tests/pages/variationSummaryPage.ts
integration_tests/plugins/index.ts
server/@types/licenceApiClientTypes.ts
server/@types/licenceApiImport/index.d.ts
server/data/communityApiClient.test.ts
server/data/communityApiClient.ts
server/data/hmppsRestClient.ts
server/data/licenceApiClient.test.ts
server/data/licenceApiClient.ts
server/routes/varyingLicences/handlers/variationSummary.test.ts
server/routes/varyingLicences/handlers/variationSummary.ts
server/routes/varyingLicences/index.ts
server/services/communityService.test.ts
server/services/communityService.ts
server/services/licenceService.test.ts
server/services/licenceService.ts

This reverts commit d1301d2d24b4a17aaf782625add9856fd6ac02b2.

Revert "CVSL 527: get pdu head contact details from delius (#303)"

---

integration_tests/mockApis/community.ts
integration_tests/pages/variationSummaryPage.ts
integration_tests/plugins/index.ts
server/@types/licenceApiClientTypes.ts
server/@types/licenceApiImport/index.d.ts
server/data/communityApiClient.test.ts
server/data/communityApiClient.ts
server/data/hmppsRestClient.ts
server/data/licenceApiClient.test.ts
server/data/licenceApiClient.ts
server/routes/varyingLicences/handlers/variationSummary.test.ts
server/routes/varyingLicences/handlers/variationSummary.ts
server/routes/varyingLicences/index.ts
server/services/communityService.test.ts
server/services/communityService.ts
server/services/licenceService.test.ts
server/services/licenceService.ts

This reverts commit 62ea61beb35fadd7a818bc55d8bbb28f5b8c3ed3.

Revert "Revert "CVSL 527: get pdu head contact details from delius (#303)" (#305)"

---

server/config/conditions.ts

New policy changes to be deployed 19th July 2022

update policy conditions in response to July 19th 2022 changes

---

server/enumeration/TimelineEventType.ts
server/services/licenceService.test.ts
server/services/licenceService.ts
server/views/pages/index.njk
server/views/pages/vary/timeline.njk
server/views/pages/vary/timeline.test.ts

These are changes requested in the the Dashboard and Licence History sections of the changes document in the ticket.

CVSL-582 vary journey design changes 1

---

server/routes/varyingLicences/index.ts
server/routes/varyingLicences/types/deleteVariation.ts
server/views/pages/vary/confirmDiscardVariation.njk

There is no change to the underlying logic.
The page title could not be presented on one line, even with full width column. 
The image in the ticket shows the title on one line but at the expense of the content below the grey line not being aligned with the other content in the page. 
The revised page:

CVSL-582 error, question and button text changed.

---

server/routes/creatingLicences/types/reasonForVariation.ts
server/views/pages/vary/reasonForVariation.njk
server/views/partials/variationDetails.njk
server/views/partials/variedConditions.njk

There is no logic change
Page view

CVSL-582 text changes

---

server/views/pages/vary/viewActive.njk
server/views/partials/additionalLicenceConditionsSummary.njk
server/views/partials/additionalPssConditionsSummary.njk
server/views/partials/bespokeConditionsSummary.njk

CVSL-582 text change for view-active page

---

server/views/pages/vary/confirmation.njk

very minor change following review by content designer

CVSL-582 change text to lower case

---

server/views/pages/index.njk
server/views/pages/vary-approve/cases.njk

Search bar for PDU head now looks like this.

CVSl 582 PDU head dashboard and case list pages

---

server/views/pages/vary-approve/variation-referred.njk

ACs
- Change banner to Licence variation for [first name last name] approved 
- Change text under What happens next to:
The licence and post sentence supervision order variation for [first name last name] has been approved with your digital signature. 
We have sent an email notification to the probation practitioner.
They will be able to print and issue the licence.
- Change green button text to "Return to case list"

CVSL minor text changes for PDU head variation approval page

---

server/routes/creatingLicences/types/reasonForVariation.ts
server/routes/varyingLicences/handlers/confirmation.test.ts
server/routes/varyingLicences/handlers/confirmation.ts
server/routes/varyingLicences/types/deleteVariation.ts
server/views/pages/vary/confirmDiscardVariation.njk
server/views/pages/vary/confirmation.njk
server/views/pages/vary/reasonForVariation.njk
server/views/pages/vary/variationSummary.njk

Changes to the Com vary journey
These are new additions to the ACs

CVSL 582 com vary journey

---

server/routes/creatingLicences/types/reasonForVariation.ts
server/views/pages/create/checkAnswers.test.ts
server/views/pages/vary-approve/cases.njk
server/views/pages/vary-approve/view.njk
server/views/partials/additionalLicenceConditionsSummary.njk
server/views/partials/additionalPssConditionsSummary.njk
server/views/partials/bespokeConditionsSummary.njk

text changes - see ticket notes dated 2/8/22

CVSL 582 vary journey design changes 2

---

server/@types/licenceApiClientTypes.ts
server/data/licenceApiClient.ts
server/routes/support/handlers/omuEmailAddress.ts
server/routes/support/index.ts
server/routes/support/types/prisonIdAndEmail.ts
server/routes/support/types/prisonIdCurrent.ts
server/routes/support/types/prisonIdDelete.ts
server/services/licenceService.ts
server/utils/nunjucksSetup.ts
server/views/layout.njk
server/views/pages/support/home.njk
server/views/pages/support/manageOmuEmailAddress.njk

CVSL-604 enable management of OMU emails

---

server/services/caseloadService.test.ts
server/services/caseloadService.ts

check PED is set and in the future before excluding record from the caseload service.

CVSL-608 check PED is set and in the future

---

server/routes/home/handlers/accessibilityStatement.ts
server/routes/home/index.ts
server/utils/nunjucksSetup.ts
server/views/layout.njk
server/views/pages/accessibilityStatement.njk

Page accessed from new Accessibility statement link in footer

CVSL-622 accessibility statement page added

---

server/views/pages/about.njk
server/views/pages/accessibilityStatement.njk
server/views/pages/contactUs.njk

and also changes to page tab titles

CVL-622 minor capitalisation and styling changes

---

jobs/emailProbationPractioner.ts

moved exception handling to parent function and added the missing 'await'

CVSL-619 refactor cron job exception handling

---

.circleci/config.yml
package-lock.json
package.json

Reduces local test run from ~2m30s to 28s
Reduces CI tests down to around ~42s (at least when run locally)

CVSL-674 Speeding up tests

---

helm_deploy/create-and-vary-a-licence/templates/email-probation-practioner-cronjob.yaml

CVSL-619 fix cron job

---

server/routes/varyingLicences/handlers/policyChange.ts
server/views/pages/create/additionalLicenceConditions.njk

Also removing banner about policy conditions

CVSL-138 Fixing typo where param wasn't being passed to method

---

jobs/promptLicenceCreation.ts

It was previously being sent for for both NOT_STARTED and IN_PROGRESS statuses

CVSL-710 initial PP email sent only for NOT_STARTED status cases

---

server/routes/viewingLicences/handlers/viewCases.test.ts
server/routes/viewingLicences/handlers/viewCases.ts
server/views/pages/view/cases.njk

Acceptance Criteria
The default sorting of the release date column on the ‘People on probation’ tab is descending

CVSL-718-probation case list now rendered in descending release date order

---

jobs/promptLicenceCreation.ts

PP to be sent an email between weeks 5 and 12 prior to release date, providing one wasn't already sent at week 13.
There isn't a way to determine whether an email was in fact sent at week 13 so the the logic implemented looks at whether there has been a change of PP during the past 7 days. If there hasn't been a new PP (determined by the 'allocation date') then it's assumed the previous PP received an email. If there has been a PP change, then it assumed this is a new PP so an email will be sent. This process will check each week during the 5-12 weeks before release date.

CVSL-709 sending email to PP between weeks 5-12 before crd

---

server/views/pages/contactUs.njk

Simple changes to static text as requested by UCD

Rewording the contact us page to better reflect new support process

---

package-lock.json
package.json

Dependency bumps to stop errors in circle

Bumping TS to v4.9.3 and govuk-frontend to v4.4.0

---

server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.test.ts
server/listeners/eventHandlers/prisonEvents/datesChangedEventHandler.ts

Stops date update events from removing CRD from IS91 cases

CVSL-667 - Preventing IS91 cases from disappearing 

---

integration_tests/integration/createLicence.spec.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts

CVSL-732 minor change of text

---

server/services/conditionFormatter.test.ts
server/services/conditionFormatter.ts
server/services/conditionService.test.ts
server/services/conditionService.ts

Extracting out formatting code and fixing test names/locations.
This is in preparation for reimplementing in the backend

CVSL-626 Extracting out formatting code

---

server/services/caseloadService.test.ts
server/services/caseloadService.ts

change from being start of current week + weeks to today + 4 weeks

CVSL-739 prison users can view cases with CRD of 4 weeks of today

---

server/views/pages/create/initialMeetingContact.njk
server/views/pages/create/initialMeetingPerson.njk
server/views/pages/create/initialMeetingPlace.njk
server/views/pages/create/initialMeetingTime.njk
server/views/pages/view/cases.njk

added missing closing div
changed page tab titles

CVSl 638 accessibility audit

---

server/views/pages/create/additionalLicenceConditions.njk

Changes made in collaboration with the design team
The only way to set the section headings as h2s was to embed them inside the legend

CVSL-636 styling change and setting of h2

---

server/views/layout.njk
server/views/pages/create/initialMeetingTime.njk
server/views/partials/timePicker.njk

H1 to be defined legend. 
Accessibility passes in Wave. 
Ignore result in Dev tools HTML validator. It erroneously suggests missing closing tag for field set.

CVSL-634 wrap with field set

---

server/views/pages/support/offenderSearch.njk
server/views/pages/vary-approve/cases.njk

minor changes identified by Wave tool

Cvsl 746 accessibility fix

---

server/views/pages/vary/policyConfirmDelete.njk

Adding backlink and making radio buttons inline on confirm delete page

Requested changes to inflight policy improvements

---

jobs/updateLicences.ts

Adding 'IMMIGRATION_DETAINEE' as a valid legal status for licences that are to be activated by the automatic job

Adding IS91 to the allowed legal statuses to be activated.

---

server/utils/utils.ts

Fixing issue where bank holiday check was failing as it was comparing datetime rather than just date

Bank holiday fix

---

server/services/caseloadService.test.ts
server/services/caseloadService.ts
server/services/licenceService.test.ts
server/services/licenceService.ts

Reverts ministryofjustice/create-and-vary-a-licence#501

Revert "CVSL-777 - Removing reference to SED in licence type logic"

---

server/views/pages/support/offenderDetail.njk

Minor improvements to support pages - inc. remove offender details

CVSL-1047-

---

integration_tests/mockApis/polices/v2-0.ts
integration_tests/mockApis/polices/v2-1.ts
server/@types/licenceApiClientTypes.ts
server/@types/licenceApiImport/index.d.ts

Now policy stubs have additional typesafety of input types

Fix policy types

---

server/views/pages/index.njk

Reverts ministryofjustice/create-and-vary-a-licence#623

Revert "CVSL-1050 Add outage banner"

---

server/routes/manageConditions/handlers/additionalLicenceConditionInput.ts
server/utils/conditionRoutes.ts
server/views/pages/create/additionalLicenceConditionInput.njk

Currently using same template for MEZ and normal conditions but will split out

CVSL-1287 Allow for swapping input template based on condition

---

server/routes/manageConditions/handlers/deleteConditionsByCodeHandler.test.ts
server/routes/manageConditions/handlers/deleteConditionsByCodeHandler.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/manageConditions/fileUploads/list.njk

Previously if you click delete condition from the list view it would drop out of the create flow. Now it should know whether in the create flow or review flow and preserve the journey

CVSL-1287 Fixing navigation bug

---

cypress.config.ts
server/@types/ukBankHolidays/index.d.ts
server/routes/creatingLicences/handlers/confirmCreate.test.ts
server/routes/creatingLicences/handlers/confirmCreate.ts
server/routes/creatingLicences/handlers/initialMeetingContact.test.ts
server/routes/creatingLicences/handlers/initialMeetingContact.ts
server/routes/creatingLicences/handlers/initialMeetingName.test.ts
server/routes/creatingLicences/handlers/initialMeetingName.ts
server/routes/creatingLicences/handlers/initialMeetingPlace.test.ts
server/routes/creatingLicences/handlers/initialMeetingPlace.ts
server/routes/creatingLicences/handlers/initialMeetingTime.test.ts
server/routes/creatingLicences/handlers/initialMeetingTime.ts
server/services/ukBankHolidayFeedService.test.ts
server/services/ukBankHolidayFeedService.ts
server/utils/utils.test.ts
server/utils/utils.ts
server/validators/dateIsAfterExpectedReleaseDate.ts
server/validators/dateIsOnWorkDay.ts

When looking at updating eslint it picked up this cyclical dependency.

CVSL-1357 Tidying up bank-holiday usage

---

.circleci/config.yml
helm_deploy/values-test2.yaml

Always deploy test2 on deploy to main

Pointing test2 to real delius

---

integration_tests/integration/eventHandlers.cy.ts
server/data/licenceApiClient.test.ts
server/data/licenceApiClient.ts
server/listeners/eventHandlers/domainEvents/releaseEventHandler.test.ts
server/listeners/eventHandlers/domainEvents/releaseEventHandler.ts
server/services/prisonerService.test.ts
server/services/prisonerService.ts

Only inactivate for HDC if there is a valid HDCED

CVSL-1429 Fixing release event handler HDC logic

---

server/routes/support/handlers/offenderDetail.ts
server/views/pages/support/offenderDetail.njk

Do not show link if OUT and no current licence

CVSL-1455 Default to licence prison id if currently out

---

server/views/pages/create/initialMeetingTime.njk

Decided to rename the script path for now rather than make the filename datePicker as the filename change wasn't being picked up as a git change. Will prob make the filename datePicker for consistency in a follow up PR when I address the other comments in the last PR: https://github.com/ministryofjustice/create-and-vary-a-licence/pull/743
This is a quick fix to get the script working in dev for now.

CVSL-868 filename fix

---

helm_deploy/create-and-vary-a-licence/values.yaml

Reverts ministryofjustice/create-and-vary-a-licence#739

Revert "Switch off new search while fixing reverting to old search"

---

.circleci/config.yml
Dockerfile
docker-compose-test.yml
package.json
server/config.ts
server/middleware/fetchLicenceMiddleware.test.ts
server/middleware/populateCurrentUser.test.ts
server/middleware/validationMiddleware.test.ts
server/routes/changeTeam/handlers/changeTeam.test.ts
server/routes/creatingLicences/handlers/caseload.test.ts
server/routes/search/handlers/probationSearch.test.ts
server/routes/support/handlers/offenderDetail.ts
server/routes/support/handlers/offenderLicenceDates.test.ts
server/routes/support/handlers/offenderLicenceStatus.test.ts
server/services/licenceService.test.ts
server/services/prisonRegisterService.test.ts
server/services/prisonerService.test.ts
server/services/searchService.test.ts

Also:
* Removing usages of deprecated test method
* Moving to use project version of node for npm security and outdated checks
* Fixing little issue on support page where the page wouldn't load if there was no associated com for an offender

CVSL-1731 Fixing local stack issue

---

server/views/partials/activateVaryLicenceReminderBanner.njk

Reverts ministryofjustice/create-and-vary-a-licence#820

Revert "CVSL-1618 reminder banner typo fix"

---

.circleci/config.yml

Always deploy HEAD of main to test1 and disable test1 branch deploy

Moving to use hard stop in test1

---

helm_deploy/values-preprod.yaml

This PR is to enable hard stop in preprod to allow for some extra testing.

CVSL-1808 enable hard stop in preprod

---

jobs/promptLicenceCreationService.test.ts
server/@types/licenceApiImport/index.d.ts
server/routes/approvingVariations/handlers/varyApproveList.test.ts
server/routes/creatingLicences/handlers/confirmCreate.test.ts
server/routes/creatingLicences/handlers/confirmCreate.ts
server/routes/creatingLicences/handlers/hardStop/confirmCreate.ts
server/routes/creatingLicences/index.ts
server/routes/varyingLicences/handlers/caseload.test.ts
server/routes/viewingLicences/handlers/viewCases.test.ts
server/routes/views/CaseloadViewModel.test.ts
server/services/omuCaselist.test.ts
server/views/pages/create/confirmCreate.njk

Moving to use the backend as a source of this flag

CVSL-1829 fix missing early release warning on hardstop create screen

---

server/@types/licenceApiImport/index.d.ts
server/routes/viewingLicences/handlers/viewCases.test.ts
server/services/caseloadService.test.ts
server/services/caseloadService.ts

This PR is to address a bug where `Last Worked On By` was not populated.

CVSL-1832 add updatedByFullName to mapping licence to offender

---

server/listeners/eventHandlers/probationEvents/index.ts

Current code was logging the exception only without any context - this should link the message and the context

CVSL-1871 fix logging

---

helm_deploy/create-and-vary-a-licence/templates/inactivate-recall-licences-cronjob.yaml
helm_deploy/create-and-vary-a-licence/values.yaml
helm_deploy/values-dev.yaml
helm_deploy/values-test1.yaml
jobs/inactivateRecallLicences.ts
server/data/licenceApiClient.ts

This PR is to add the job to inactivate active licences and their variations where a PRRD has been entered, meaning the person has been recalled.

CVSL-1738 add inactivate recall job to FE

---

integration_tests/mockApis/licence.ts
server/@types/licenceApiImport/index.d.ts
server/routes/viewingLicences/handlers/viewCases.test.ts
server/routes/viewingLicences/handlers/viewCases.ts
server/services/lists/caCaseloadService.test.ts

Reverts ministryofjustice/create-and-vary-a-licence#1013

Revert "CVSL-1910-date-format-fix"

---

server/validators/dateIsAfterExpectedReleaseDate.ts

Validator to be reinstated in future

CVSL-2052 Removing CRD validations in advance of SDS40

---

integration_tests/mockApis/licence.ts
server/@types/licenceApiImport/index.d.ts
server/routes/viewingLicences/handlers/viewCases.test.ts
server/routes/viewingLicences/handlers/viewCases.ts
server/services/lists/caCaseloadService.test.ts

Reverts ministryofjustice/create-and-vary-a-licence#1015

Revert "Revert "CVSL-1910-date-format-fix""

---

integration_tests/mockApis/licence.ts
server/@types/licenceApiImport/index.d.ts
server/routes/viewingLicences/handlers/viewCases.test.ts
server/routes/viewingLicences/handlers/viewCases.ts
server/services/lists/caCaseloadService.test.ts

Reverts ministryofjustice/create-and-vary-a-licence#1032

Revert "Revert "Revert "Revert "CVSL-1910-date-format-fix""""

---

cypress.config.ts
integration_tests/integration/createLicence.cy.ts
integration_tests/integration/varyLicence.cy.ts
integration_tests/mockApis/licence.ts
server/data/licenceApiClient.ts
server/routes/manageConditions/handlers/curfew/curfewRoutes.test.ts
server/routes/manageConditions/handlers/curfew/curfewRoutes.ts
server/routes/manageConditions/handlers/deleteConditionsByCodeHandler.test.ts
server/routes/manageConditions/handlers/deleteConditionsByCodeHandler.ts
server/routes/varyingLicences/handlers/policyChange.test.ts
server/routes/varyingLicences/handlers/policyChange.ts
server/services/conditionService.ts
server/services/licenceService.ts

Should only be deployed after the corresponding [API changes](https://github.com/ministryofjustice/create-and-vary-a-licence-api/pull/575)

CVSL-2056 Fixing 500 error during policy upgrade when two deleted conditions existed on a licence

---

helm_deploy/create-and-vary-a-licence/values.yaml

This PR is to update the URL for ServiceNow.

CVSL-2113 change url for service now

---

server/enumeration/fileUploadType.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadInputRoutes.test.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadInputRoutes.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadListRoutes.test.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadListRoutes.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadRemovalRoutes.test.ts
server/routes/manageConditions/handlers/fileUploads/fileUploadRemovalRoutes.ts
server/routes/manageConditions/handlers/fileUploads/index.ts
server/views/pages/manageConditions/fileUploads/list.njk

Also fixes some 'fromReview' routing for MEZ

CVSL-2151 Adding correct routing for map upload conditions to redirect back to policy review flow when appropriate

---

server/views/pages/manageConditions/fileUploads/list.njk

Comparison of new and old styling can be seen here:
This design has been signed off by UCD

CVSL-2181 Changing content and layout of MEZ list screen for maps without names (as will be in policy v3)

---

server/views/partials/whatsNewBanner.njk

Note: The banner is not currently turned on, just updating the content for when we flip the switch

CVSL-2233 Updating banner content for after policy v3 release

---

server/validators/dateIsAfterExpectedReleaseDate.ts

Reverts ministryofjustice/create-and-vary-a-licence#1018

CVSL-2053 Re-add validations after SDS40

---

server/@types/licenceApiImport/index.d.ts
server/routes/creatingLicences/handlers/checkAnswers.test.ts
server/routes/creatingLicences/handlers/checkAnswers.ts
server/routes/creatingLicences/index.ts
server/routes/viewingLicences/handlers/printLicence.test.ts
server/services/hdcService.test.ts
server/services/hdcService.ts
server/utils/nunjucksSetup.ts
server/views/pages/create/checkAnswers.njk
server/views/pages/create/checkAnswers.test.ts
server/views/pages/licence/partials/hdcCurfewTimes.njk

CVSL-2333 Adding curfew details to check your answers page for HDC licences

---

server/views/pages/create/hardStop/initialMeetingTime.njk
server/views/pages/create/initialMeetingTime.njk
server/views/partials/hdc/hdcInitialMeetingTimeInputs.njk

This additional PR follows on from https://github.com/ministryofjustice/create-and-vary-a-licence/pull/1121 to change the heading to match the new designs.

CVSL-2323 adjust inital meeting time heading text

---

server/routes/support/handlers/offenderDetail.test.ts
server/routes/support/handlers/offenderDetail.ts
server/views/pages/support/offenderDetail.njk

Small IS-91 content change for more consistency

CVSL-2521 small IS-91 content change and determine Yes No in route handler

---

server/views/pages/support/probationStaff.njk
server/views/pages/support/probationTeam.njk

https://dsdmoj.atlassian.net/browse/CVSL-2766

Show 'HDC release' lable on support views

---

integration_tests/integration/approveLicence.cy.ts
server/routes/creatingLicences/types/date.ts
server/services/licenceService.test.ts
server/utils/nunjucksSetup.test.ts
server/utils/nunjucksSetup.ts
server/views/pages/approve/InitialAppointment.njk
server/views/pages/approve/keyDates.njk
server/views/pages/approve/prisonerSummaryDetails.njk
server/views/pages/create/checkAnswers.njk
server/views/pages/manageConditions/additionalPssConditionInput.njk
server/views/pages/support/offenderLicenceDates.njk
server/views/pages/vary/confirmVaryQuestion.njk
server/views/pages/vary/viewActive.njk
server/views/partials/hardStop/inductionMeetingDetailsSummary.njk
server/views/partials/inductionMeetingDetailsSummary.njk
server/views/partials/licenceDetailsBanner.njk
server/views/partials/variationDetails.njk

Reverts ministryofjustice/create-and-vary-a-licence#1312

Revert "Cvsl 1888 date format"

---

server/views/pages/support/offenderLicences.njk

This PR is to surface kind on the licence table in support.

CVSL-3004 add kind to licence table
